
.PHONY: all clean cleanall

all:
	@$(MAKE) -C array
	@$(MAKE) -C list
	@$(MAKE) -C list-r
	@$(MAKE) -C queue
	@$(MAKE) -C queue-array
	@$(MAKE) -C stack
	@$(MAKE) -C prefix-tree

clean:
	@$(MAKE) clean -C array
	@$(MAKE) clean -C list
	@$(MAKE) clean -C list-r
	@$(MAKE) clean -C queue
	@$(MAKE) clean -C queue-array
	@$(MAKE) clean -C stack
	@$(MAKE) clean -C prefix-tree

cleanall:
	@$(MAKE) cleanall -C array
	@$(MAKE) cleanall -C list
	@$(MAKE) cleanall -C list-r
	@$(MAKE) cleanall -C queue
	@$(MAKE) cleanall -C queue-array
	@$(MAKE) cleanall -C stack
	@$(MAKE) cleanall -C prefix-tree
