#!/bin/bash -e

SERVICE="echod"

echo -n "Enabling $SERVICE... "
/bin/systemctl enable $SERVICE >/dev/null 2>&1 || {
	echo "FAILED"
	exit 1
}
echo "Ok"

echo -n "Starting $SERVICE... "
/bin/systemctl start $SERVICE >/dev/null 2>&1 || {
	echo "FAILED"
	exit 1
}
echo "Ok"

exit 0
