#!/bin/bash -e

SERVICE="echod"

echo -n "Stopping $SERVICE... "
/bin/systemctl stop $SERVICE >/dev/null 2>&1 || {
	echo "FAILED"
	exit 1
}
echo "Ok"

echo -n "Disabling $SERVICE... "
/bin/systemctl disable $SERVICE >/dev/null 2>&1 || {
	echo "FAILED"
	exit 1
}
echo "Ok"

exit 0
